shaima:
    path:     /page
    defaults: { _controller: ShaimaBundle:Default:page }
layout:
    path:     /layout
    defaults: { _controller: ShaimaBundle:Default:layout }
layoutF:
  path:     /layoutF
  defaults: { _controller: ShaimaBundle:Default:layoutF }
wight:
  path:     /wight
  defaults: { _controller: ShaimaBundle:Default:wigh }
AfficherStock:
  path:     /AfficherStock
  defaults: { _controller: ShaimaBundle:Default:afficheStock }
deleteStock:
  path:     /deleteStock/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteStock }
ajouterStock:
  path:     /ajouterStock
  defaults: { _controller: ShaimaBundle:Default:ajouterStock }
modifierStock:
  path:     /modifierStock/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierStock }
AfficherMeuble:
  path:     /AfficherMeuble
  defaults: { _controller: ShaimaBundle:Default:afficheMeuble }
ajouterMeuble:
  path:     /ajouterMeuble
  defaults: { _controller: ShaimaBundle:Default:AjouterMeuble}
deleteMeuble:
  path:     /deleteMeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteMeuble }
modifiermeuble:
  path:     /modifiermeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierMeuble }
refugee_afficherDetasille:
  path:     /pdf
  defaults: { _controller: ShaimaBundle:Default:pdf }
refugee_afficherDetaille:
  path:     /afficherD/{id}
  defaults: { _controller: ShaimaBundle:Default:afficherDetaille }
AfficherMeubleF:
  path:     /AfficherMeubleF
  defaults: { _controller: ShaimaBundle:Default:afficheMeubleF }
AchatAdd:
  path:     /addachat/{id}
  defaults: { _controller: ShaimaBundle:Default:addAchat}

afficheLivraison:
  path:     /afficheLivraison
  defaults: { _controller: ShaimaBundle:Default:afficheLivraison }

afficheMLivraison:
  path:     /afficheMLivraison
  defaults: { _controller: ShaimaBundle:Default:afficheMLivraison }
CommandeAdd:
  path:     /addCommande
  defaults: { _controller: ShaimaBundle:Default:addCommande}
deleteMl:
  path:     /deleteML/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteML }
modifierML:
  path:     /modifierML/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierML }
Notif:
  path:     /Notif
  defaults: { _controller: ShaimaBundle:Default:afficheNotif }
map:
  path:     /map
  defaults: { _controller: ShaimaBundle:Default:Map }
home:
  path:     /
  defaults: { _controller: ShaimaBundle:Default:home }
register:
  path:     /register
  defaults: { _controller: ShaimaBundle:Default:register }