AfficherStockh:
  path:     /
  defaults: { _controller: ShaimaBundle:Default:afficheStock }
shaima:
    path:     /page
    defaults: { _controller: ShaimaBundle:Default:page }
layout:
    path:     /layout
    defaults: { _controller: ShaimaBundle:Default:layout }
wight:
  path:     /wight
  defaults: { _controller: ShaimaBundle:Default:wigh }
AfficherStock:
  path:     /AfficherStock
  defaults: { _controller: ShaimaBundle:Default:afficheStock }
deleteStock:
  path:     /deleteStock/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteStock }
ajouterStock:
  path:     /ajouterStock
  defaults: { _controller: ShaimaBundle:Default:ajouterStock }
modifierStock:
  path:     /modifierStock/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierStock }
AfficherMeuble:
  path:     /AfficherMeuble
  defaults: { _controller: ShaimaBundle:Default:afficheMeuble }
ajouterMeuble:
  path:     /ajouterMeuble
  defaults: { _controller: ShaimaBundle:Default:AjouterMeuble}
deleteMeuble:
  path:     /deleteMeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteMeuble }
modifiermeuble:
  path:     /modifiermeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierMeuble }
refugee_afficherDetasille:
  path:     /pdf
  defaults: { _controller: ShaimaBundle:Default:pdf }
refugee_afficherDetaille:
  path:     /afficherD/{id}
  defaults: { _controller: ShaimaBundle:Default:afficherDetaille }
