shaima:
    path:     /page
    defaults: { _controller: ShaimaBundle:Default:page }
layout:
    path:     /layout
    defaults: { _controller: ShaimaBundle:Default:layout }
layoutF:
  path:     /layoutF
  defaults: { _controller: ShaimaBundle:Default:layoutF }
wight:
  path:     /wight
  defaults: { _controller: ShaimaBundle:Default:wigh }
AfficherStock:
  path:     /admin/AfficherStock
  defaults: { _controller: ShaimaBundle:Default:afficheStock }
deleteStock:
  path:     /admin/deleteStock/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteStock }
ajouterStock:
  path:     /admin/ajouterStock
  defaults: { _controller: ShaimaBundle:Default:ajouterStock }
modifierStock:
  path:     /admin/modifierStock/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierStock }
AfficherMeuble:
  path:     /admin/AfficherMeuble
  defaults: { _controller: ShaimaBundle:Default:afficheMeuble }
ajouterMeuble:
  path:     /admin/ajouterMeuble
  defaults: { _controller: ShaimaBundle:Default:AjouterMeuble}
deleteMeuble:
  path:     /admin/deleteMeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteMeuble }
modifiermeuble:
  path:     /admin/modifiermeuble/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierMeuble }
imprimer:
  path:     /admin/pdf
  defaults: { _controller: ShaimaBundle:Default:pdf }
refugee_afficherDetaille:
  path:     /admin/afficherD/{id}
  defaults: { _controller: ShaimaBundle:Default:afficherDetaille }
AfficherMeubleF:
  path:     /AfficherMeubleF
  defaults: { _controller: ShaimaBundle:Default:afficheMeubleF }
AchatAdd:
  path:     /admin/addachat/{id}
  defaults: { _controller: ShaimaBundle:Default:addAchat}

afficheLivraison:
  path:     /admin/afficheLivraison
  defaults: { _controller: ShaimaBundle:Default:afficheLivraison }

afficheMLivraison:
  path:     /admin/afficheMLivraison
  defaults: { _controller: ShaimaBundle:Default:afficheMLivraison }
CommandeAdd:
  path:     /addMLivraison
  defaults: { _controller: ShaimaBundle:Default:addMLivraison}
deleteMl:
  path:     /deleteML/{id}
  defaults: { _controller: ShaimaBundle:Default:deleteML }
modifierML:
  path:     /modifierML/{id}
  defaults: { _controller: ShaimaBundle:Default:modifierML }
Notif:
  path:     /admin/Notif
  defaults: { _controller: ShaimaBundle:Default:afficheNotif }
map:
  path:     /map
  defaults: { _controller: ShaimaBundle:Default:Map }
home:
  path:     /
  defaults: { _controller: ShaimaBundle:Default:home }
register:
  path:     /register
  defaults: { _controller: ShaimaBundle:Default:register }