<?php

namespace ShaimaBundle\Repository;

/**
 * livraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
